export type DownloadErrorCode =
  | "E_ABORTED"
  | "E_AUTH_REQUIRED"
  | "E_DIRECT_SOURCE_REQUIRED"
  | "E_ENGINE_NOT_FOUND"
  | "E_ENGINE_REJECTED_INTENT"
  | "E_ENGINE_UNAVAILABLE"
  | "E_EXECUTION_FAILED"
  | "E_INVALID_DOWNLOAD_INPUT"
  | "E_INVALID_ENGINE_PLAN"
  | "E_INVALID_INTENT"
  | "E_NO_ENGINE_SUCCEEDED"
  | "E_NO_PROVIDER_MATCH"
  | "E_OUTPUT_NOT_FOUND";
